import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { sessionsApi, githubApi, API_BASE_URL } from '@/lib/api';
import { useEventSource } from '@/hooks/useEventSource';
import { useAuthStore } from '@/lib/store';
import ChatInput, { type ChatInputRef, type ImageAttachment } from '@/components/ChatInput';
import { ImageViewer } from '@/components/ImageViewer';
import SessionLayout from '@/components/SessionLayout';
import type { Message, GitHubRepository, ChatSession } from '@webedt/shared';

export default function Chat() {
  const { sessionId } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const queryClient = useQueryClient();
  const user = useAuthStore((state) => state.user);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [images, setImages] = useState<ImageAttachment[]>([]);
  const [selectedRepo, setSelectedRepo] = useState('');
  const [baseBranch, setBaseBranch] = useState('main');
  const [isExecuting, setIsExecuting] = useState(false);
  const [streamUrl, setStreamUrl] = useState<string | null>(null);
  const [streamMethod, setStreamMethod] = useState<'GET' | 'POST'>('GET');
  const [streamBody, setStreamBody] = useState<any>(null);
  const [editingTitle, setEditingTitle] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [deletingSession, setDeletingSession] = useState(false);
  const [currentSessionId, setCurrentSessionId] = useState<number | null>(() => {
    if (!sessionId || sessionId === 'new') return null;
    const parsed = Number(sessionId);
    return isNaN(parsed) ? null : parsed;
  });
  const [aiWorkerSessionId, setAiWorkerSessionId] = useState<string | null>(null);
  const [isLocked, setIsLocked] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messageIdCounter = useRef(0);
  const autoGeneratedTitleRef = useRef<string | null>(null);
  const hasUserEditedTitleRef = useRef(false);
  const chatInputRef = useRef<ChatInputRef>(null);
  const titlePollIntervalRef = useRef<NodeJS.Timeout | null>(null);
  const [lastRequest, setLastRequest] = useState<{
    input: string;
    selectedRepo: string;
    baseBranch: string;
  } | null>(null);
  const [viewingImage, setViewingImage] = useState<{
    data: string;
    mediaType: string;
    fileName: string;
  } | null>(null);

  // Load session details first to check status
  const { data: sessionDetailsData } = useQuery({
    queryKey: ['session-details', sessionId],
    queryFn: () => {
      const id = Number(sessionId);
      if (isNaN(id)) {
        throw new Error('Invalid session ID');
      }
      return sessionsApi.get(id);
    },
    enabled: !!sessionId && sessionId !== 'new',
    // Poll every 2 seconds if session is running or pending
    refetchInterval: (query) => {
      const session = query.state.data?.data;
      return session?.status === 'running' || session?.status === 'pending' ? 2000 : false;
    },
  });

  // Load existing session messages if sessionId provided
  const { data: sessionData } = useQuery({
    queryKey: ['session', sessionId],
    queryFn: () => {
      const id = Number(sessionId);
      if (isNaN(id)) {
        throw new Error('Invalid session ID');
      }
      return sessionsApi.getMessages(id);
    },
    enabled: !!sessionId && sessionId !== 'new',
    // Poll every 2 seconds if session is running or pending, but NOT while SSE stream is active
    // This prevents duplicate messages from both SSE and polling
    refetchInterval: () => {
      // Don't poll while SSE stream is active to avoid duplicates
      if (isExecuting) return false;

      const session = sessionDetailsData?.data;
      return session?.status === 'running' || session?.status === 'pending' ? 2000 : false;
    },
  });

  const session: ChatSession | undefined = sessionDetailsData?.data;

  // Load current session details to check if locked
  const { data: currentSessionData } = useQuery({
    queryKey: ['currentSession', currentSessionId],
    queryFn: async () => {
      if (!currentSessionId || currentSessionId === 0 || isNaN(currentSessionId)) return null;
      const response = await fetch(`${API_BASE_URL}/api/sessions/${currentSessionId}`, {
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to fetch session');
      return response.json();
    },
    enabled: !!currentSessionId && currentSessionId !== 0 && !isNaN(currentSessionId),
  });

  // Load repositories
  const { data: reposData, isLoading: isLoadingRepos } = useQuery({
    queryKey: ['repos'],
    queryFn: githubApi.getRepos,
    enabled: !!user?.githubAccessToken,
  });

  const repositories: GitHubRepository[] = reposData?.data || [];

  const updateMutation = useMutation({
    mutationFn: ({ id, title }: { id: number; title: string }) =>
      sessionsApi.update(id, title),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['session-details', sessionId] });
      queryClient.invalidateQueries({ queryKey: ['sessions'] });
      setEditingTitle(false);
      setEditTitle('');
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => sessionsApi.delete(id),
    onSuccess: () => {
      navigate('/dashboard');
    },
  });

  const handleEditTitle = () => {
    if (session) {
      setEditTitle(session.userRequest);
      setEditingTitle(true);
    }
  };

  const handleSaveTitle = () => {
    if (sessionId && editTitle.trim()) {
      hasUserEditedTitleRef.current = true;
      updateMutation.mutate({ id: Number(sessionId), title: editTitle.trim() });
    }
  };

  const handleCancelEdit = () => {
    setEditingTitle(false);
    setEditTitle('');
  };

  const handleDeleteSession = () => {
    setDeletingSession(true);
  };

  const confirmDelete = () => {
    if (sessionId) {
      deleteMutation.mutate(Number(sessionId));
    }
  };

  const cancelDelete = () => {
    setDeletingSession(false);
  };

  // Handle Enter key in delete modal
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (deletingSession && e.key === 'Enter' && !deleteMutation.isPending) {
        e.preventDefault();
        confirmDelete();
      }
    };

    if (deletingSession) {
      window.addEventListener('keydown', handleKeyDown);
      return () => window.removeEventListener('keydown', handleKeyDown);
    }
  }, [deletingSession, deleteMutation.isPending]);

  useEffect(() => {
    if (sessionData?.data?.messages) {
      setMessages(sessionData.data.messages);
    }
  }, [sessionData]);

  // Update locked state and repository settings when session data changes
  useEffect(() => {
    if (currentSessionData?.data) {
      // Set lock state from database
      if (currentSessionData.data.locked) {
        setIsLocked(true);
      }

      // Always populate repository settings from session data when available
      // This ensures the second bar shows values even before the session is locked
      if (currentSessionData.data.repositoryUrl) {
        setSelectedRepo(currentSessionData.data.repositoryUrl);
      }
      if (currentSessionData.data.baseBranch) {
        setBaseBranch(currentSessionData.data.baseBranch);
      }
    }
  }, [currentSessionData]);

  // Auto-lock repository controls when messages exist (active session)
  // This ensures controls are only editable on the NewSession page
  useEffect(() => {
    if (messages.length > 0 && !isLocked) {
      console.log('[Chat] Auto-locking repository controls - active session with messages');
      setIsLocked(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messages.length]); // Only depend on messages.length to prevent re-render loops

  // Load last selected repo from localStorage when repositories are loaded (only once)
  const [hasLoadedFromStorage, setHasLoadedFromStorage] = useState(false);
  useEffect(() => {
    // Only load from localStorage if session is not locked and hasn't been loaded yet
    if (repositories.length > 0 && !hasLoadedFromStorage && !isLocked) {
      const lastSelectedRepo = localStorage.getItem('lastSelectedRepo');
      if (lastSelectedRepo) {
        // Verify the repo still exists in the list
        const repoExists = repositories.some(repo => repo.cloneUrl === lastSelectedRepo);
        if (repoExists) {
          setSelectedRepo(lastSelectedRepo);
        }
      }
      setHasLoadedFromStorage(true);
    }
  }, [repositories, hasLoadedFromStorage, isLocked]);

  // Save selected repo to localStorage whenever it changes (including clearing)
  useEffect(() => {
    if (hasLoadedFromStorage && !isLocked) {
      if (selectedRepo) {
        localStorage.setItem('lastSelectedRepo', selectedRepo);
      } else {
        localStorage.removeItem('lastSelectedRepo');
      }
    }
  }, [selectedRepo, hasLoadedFromStorage, isLocked]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Reset state when navigating to new chat (sessionId becomes undefined)
  useEffect(() => {
    if (!sessionId) {
      setMessages([]);
      setInput('');
      setImages([]);
      setSelectedRepo('');
      setIsExecuting(false);
      setStreamUrl(null);
      setEditingTitle(false);
      setEditTitle('');
      setDeletingSession(false);
      setCurrentSessionId(null);
      setAiWorkerSessionId(null);
      setIsLocked(false);
      setLastRequest(null);
      messageIdCounter.current = 0;
      autoGeneratedTitleRef.current = null;
      hasUserEditedTitleRef.current = false;
    }
  }, [sessionId]);

  // Cleanup title polling interval on unmount or session change
  useEffect(() => {
    return () => {
      if (titlePollIntervalRef.current) {
        console.log('[Chat] Cleaning up title poll interval');
        clearInterval(titlePollIntervalRef.current);
        titlePollIntervalRef.current = null;
      }
    };
  }, [sessionId]);

  // Sync aiWorkerSessionId from query data when loading an existing session
  useEffect(() => {
    if (currentSessionData?.data?.aiWorkerSessionId) {
      console.log(
        '[Chat] Syncing aiWorkerSessionId from query:',
        currentSessionData.data.aiWorkerSessionId
      );
      setAiWorkerSessionId(currentSessionData.data.aiWorkerSessionId);
    }
  }, [currentSessionData]);

  // Handle pre-selected settings from NewSession hub
  useEffect(() => {
    const state = location.state as any;

    // Check for pre-selected settings from NewSession hub
    if (state?.preSelectedSettings && !currentSessionId) {
      const { repositoryUrl, baseBranch: preSelectedBaseBranch, locked } = state.preSelectedSettings;

      console.log('[Chat] Loading pre-selected settings:', state.preSelectedSettings);

      if (repositoryUrl) {
        setSelectedRepo(repositoryUrl);
      }

      if (preSelectedBaseBranch) {
        setBaseBranch(preSelectedBaseBranch);
      }

      if (locked) {
        setIsLocked(true);
      }

      // Clear the navigation state to prevent re-applying
      navigate(location.pathname, { replace: true, state: {} });
      return;
    }

    // Check if we came from Dashboard with stream params (old behavior for backward compatibility)
    if (state?.startStream && state?.streamParams && !streamUrl) {
      console.log('[Chat] Auto-starting stream from navigation state:', state.streamParams);

      // Always use POST
      setStreamMethod('POST');
      setStreamBody(state.streamParams);
      setStreamUrl(`${API_BASE_URL}/api/execute`);

      setIsExecuting(true);

      // Clear the navigation state to prevent re-triggering
      navigate(location.pathname, { replace: true, state: {} });
    }
  }, [location.state, streamUrl, navigate, location.pathname, currentSessionId]);

  // Reset title edit tracking when switching to a different session
  useEffect(() => {
    if (sessionId) {
      autoGeneratedTitleRef.current = null;
      hasUserEditedTitleRef.current = false;
    }
  }, [sessionId]);

  const { isConnected } = useEventSource(streamUrl, {
    method: streamMethod,
    body: streamBody,
    onMessage: (event) => {
      // Log all events to see what we're receiving
      console.log('Received SSE event:', event);
      console.log('Full event data structure:', JSON.stringify(event, null, 2));

      const { eventType, data } = event;

      // Handle session-created event - update URL to the actual session ID
      if (eventType === 'session-created' && data?.chatSessionId) {
        console.log('[Chat] Session created with ID:', data.chatSessionId);
        setCurrentSessionId(data.chatSessionId);

        // Navigate to the actual session URL if we're on /session/new
        if (!sessionId || sessionId === 'new') {
          console.log('[Chat] Navigating to session:', data.chatSessionId);
          // Preserve the section path (e.g., /session/new/chat -> /session/{id}/chat)
          const currentPath = location.pathname;
          const section = currentPath.split('/').pop(); // Get the last segment
          const targetPath = section && section !== 'new'
            ? `/session/${data.chatSessionId}/${section}`
            : `/session/${data.chatSessionId}/chat`;
          navigate(targetPath, { replace: true });
        }

        // Don't display this as a message
        return;
      }

      // Capture AI worker session ID from connected event
      if (eventType === 'connected' && data?.sessionId) {
        console.log('[Chat] Captured aiWorkerSessionId from connected event:', data.sessionId);
        setAiWorkerSessionId(data.sessionId);
      }

      // Skip system events (but NOT commit_progress or github_pull_progress)
      if (eventType === 'connected' || eventType === 'completed') {
        return;
      }

      // Extract content from various possible locations
      let content: string | null = null;
      let messageType: 'assistant' | 'system' = 'assistant';
      let eventLabel = '';

      // Skip if data is undefined or null
      if (!data) {
        console.log('Skipping event with no data:', event);
        return;
      }

      // Handle git commit and pull progress events
      if (eventType === 'commit_progress') {
        content = typeof data === 'string' ? data : (data.message || JSON.stringify(data));
        eventLabel = '📤';
        messageType = 'system';
      } else if (eventType === 'github_pull_progress') {
        content = typeof data === 'string' ? data : (data.message || JSON.stringify(data));
        eventLabel = '⬇️';
        messageType = 'system';
      }
      // Extract content from different event types (matching server-side logic)
      else if (data.type === 'message' && data.message) {
        content = data.message;
        eventLabel = '💬';
      } else if (data.type === 'session_name' && data.sessionName) {
        // Session name - auto-save if not manually edited
        const newTitle = data.sessionName;
        content = `Session: ${newTitle}`;
        eventLabel = '📝';

        // Auto-update the session title if:
        // 1. User hasn't manually edited the title
        // 2. Current title is the default "Resumed session" OR matches a previous auto-generated title
        if (sessionId && session && !hasUserEditedTitleRef.current) {
          const currentTitle = session.userRequest;
          const isDefaultTitle = currentTitle === 'Resumed session';
          const isPreviousAutoTitle = autoGeneratedTitleRef.current && currentTitle === autoGeneratedTitleRef.current;

          if (isDefaultTitle || isPreviousAutoTitle || !autoGeneratedTitleRef.current) {
            console.log('[Chat] Auto-updating session title to:', newTitle);
            autoGeneratedTitleRef.current = newTitle;
            updateMutation.mutate({ id: Number(sessionId), title: newTitle });
          }
        }
      } else if (data.type === 'assistant_message' && data.data) {
        const msgData = data.data;

        // Handle assistant message with Claude response
        if (msgData.type === 'assistant' && msgData.message?.content) {
          const contentBlocks = msgData.message.content;
          if (Array.isArray(contentBlocks)) {
            const textParts = contentBlocks
              .filter((block: any) => block.type === 'text' && block.text)
              .map((block: any) => block.text);
            if (textParts.length > 0) {
              content = textParts.join('\n');
              eventLabel = '🤖';
            }
          }
        }
        // Skip result type - content already displayed from assistant message
        else if (msgData.type === 'result') {
          console.log('[Chat] Skipping result message (already displayed from assistant message)');
          return;
        }
        // Skip system init messages
        else if (msgData.type === 'system' && msgData.subtype === 'init') {
          console.log('[Chat] Skipping system init message');
          return;
        }
      }
      // Fallback to direct fields
      else if (typeof data === 'string') {
        content = data;
      } else if (data.message) {
        content = data.message;
      } else if (data.content) {
        if (Array.isArray(data.content)) {
          const textBlocks = data.content
            .filter((block: any) => block.type === 'text' && block.text)
            .map((block: any) => block.text);
          if (textBlocks.length > 0) {
            content = textBlocks.join('\n');
          }
        } else if (typeof data.content === 'string') {
          content = data.content;
        }
      } else if (data.text) {
        content = data.text;
      } else if (data.result) {
        content = typeof data.result === 'string' ? data.result : JSON.stringify(data.result, null, 2);
      }

      // Skip if no meaningful content
      if (!content) {
        console.log('Skipping event with no content:', event);
        console.log('Data keys:', typeof data === 'object' ? Object.keys(data) : typeof data);
        return;
      }

      // Add event label if present
      const finalContent = eventLabel ? `${eventLabel}\n${content}` : content;

      messageIdCounter.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + messageIdCounter.current,
          chatSessionId: Number(sessionId) || 0,
          type: messageType,
          content: finalContent,
          timestamp: new Date(),
        },
      ]);
    },
    onConnected: () => {
      setIsExecuting(true);
    },
    onCompleted: (data) => {
      setIsExecuting(false);
      setStreamUrl(null);
      // Capture session ID from completion event
      if (data?.chatSessionId) {
        console.log('[Chat] Execution completed, setting currentSessionId:', data.chatSessionId);
        setCurrentSessionId(data.chatSessionId);
        // Lock the fields after first submission completes
        // This prevents users from changing repo/branch after a session has started
        if (!isLocked && selectedRepo) {
          console.log('[Chat] Locking fields after first submission');
          setIsLocked(true);
        }
        // Invalidate queries to refetch session data and messages from database
        // This syncs the final state after SSE stream completes
        queryClient.invalidateQueries({ queryKey: ['currentSession', data.chatSessionId] });
        queryClient.invalidateQueries({ queryKey: ['session', String(data.chatSessionId)] });

        // Poll for generated title every 3 seconds for up to 60 seconds
        // (Title generation happens in background and completes ~15-20s after main request)
        const sessionIdToCheck = String(data.chatSessionId);

        // Start polling after a short delay to allow navigation and initial query to complete
        setTimeout(async () => {
          // First, ensure we have the initial session data loaded
          await queryClient.refetchQueries({ queryKey: ['session-details', sessionIdToCheck] });

          // Get initial title to compare against
          const getInitialTitle = () => {
            const sessionData = queryClient.getQueryData(['session-details', sessionIdToCheck]) as any;
            return sessionData?.data?.userRequest || '';
          };

          const initialTitle = getInitialTitle();
          console.log('[Chat] Starting title poll, initial title:', initialTitle);

          let pollAttempts = 0;
          const maxPollAttempts = 20; // 20 attempts * 3 seconds = 60 seconds max

          // Clear any existing title poll interval
          if (titlePollIntervalRef.current) {
            clearInterval(titlePollIntervalRef.current);
          }

          titlePollIntervalRef.current = setInterval(async () => {
            pollAttempts++;
            console.log(`[Chat] Polling for title update (attempt ${pollAttempts}/${maxPollAttempts})...`);

            // Refetch both queries in parallel to avoid blocking
            await Promise.all([
              queryClient.refetchQueries({ queryKey: ['session-details', sessionIdToCheck] }),
              queryClient.refetchQueries({ queryKey: ['sessions'] }),
            ]);

            // Check if title has changed
            const currentTitle = getInitialTitle();
            console.log('[Chat] Current title after refetch:', currentTitle);

            if (currentTitle && currentTitle !== initialTitle) {
              console.log('[Chat] Title updated! Stopping poll.');
              if (titlePollIntervalRef.current) {
                clearInterval(titlePollIntervalRef.current);
                titlePollIntervalRef.current = null;
              }
            } else if (pollAttempts >= maxPollAttempts) {
              console.log('[Chat] Max poll attempts reached, stopping poll.');
              if (titlePollIntervalRef.current) {
                clearInterval(titlePollIntervalRef.current);
                titlePollIntervalRef.current = null;
              }
            }
          }, 3000);
        }, 1000); // 1 second delay to allow navigation and query to load

        // Navigate to the session URL if not already there
        if (!sessionId || Number(sessionId) !== data.chatSessionId) {
          console.log('[Chat] Navigating to session:', data.chatSessionId);
          // Preserve the section path (e.g., /session/new/chat -> /session/{id}/chat)
          const currentPath = location.pathname;
          const section = currentPath.split('/').pop(); // Get the last segment
          const targetPath = section && section !== 'new' && section !== String(data.chatSessionId)
            ? `/session/${data.chatSessionId}/${section}`
            : `/session/${data.chatSessionId}/chat`;
          navigate(targetPath, { replace: true });
        }
      }
      // Refocus input after processing completes (with delay to ensure DOM updates)
      setTimeout(() => {
        chatInputRef.current?.focus();
      }, 100);
    },
    onError: (error) => {
      console.error('Stream error:', error);
      messageIdCounter.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + messageIdCounter.current,
          chatSessionId: Number(sessionId) || 0,
          type: 'error',
          content: error.message,
          timestamp: new Date(),
        },
      ]);
      setIsExecuting(false);
      setStreamUrl(null);
      // Refocus input after error (with delay to ensure DOM updates)
      setTimeout(() => {
        chatInputRef.current?.focus();
      }, 100);
    },
    autoReconnect: false, // Disable auto-reconnect to prevent infinite loops
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if ((!input.trim() && images.length === 0) || isExecuting) return;

    // Set executing state immediately to prevent duplicate submissions
    setIsExecuting(true);

    // Save last request for retry functionality
    setLastRequest({
      input: input.trim(),
      selectedRepo,
      baseBranch,
    });

    // Add user message
    messageIdCounter.current += 1;
    const userMessage: Message = {
      id: Date.now() + messageIdCounter.current,
      chatSessionId: Number(sessionId) || 0,
      type: 'user',
      content: input.trim() || (images.length > 0 ? `[${images.length} image${images.length > 1 ? 's' : ''} attached]` : ''),
      images: images.length > 0 ? images : undefined,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);

    // Build userRequest - either string or content blocks
    let userRequestParam: string | any[];

    if (images.length > 0) {
      // Create content blocks for multimodal request
      const contentBlocks: any[] = [];

      // Add text block if there's text
      if (input.trim()) {
        contentBlocks.push({
          type: 'text',
          text: input.trim(),
        });
      }

      // Add image blocks
      images.forEach((image) => {
        contentBlocks.push({
          type: 'image',
          source: {
            type: 'base64',
            media_type: image.mediaType,
            data: image.data,
          },
        });
      });

      userRequestParam = contentBlocks;
    } else {
      userRequestParam = input.trim();
    }

    // Build request parameters
    const requestParams: any = {
      userRequest: userRequestParam,
    };

    if (currentSessionId) {
      requestParams.chatSessionId = currentSessionId;
      console.log('[Chat] Continuing existing chatSession:', currentSessionId);
    }

    console.log('[Chat] Session resumption check:', {
      currentSessionId,
      aiWorkerSessionId,
      fromQuery: currentSessionData?.data?.aiWorkerSessionId,
    });

    if (aiWorkerSessionId) {
      requestParams.resumeSessionId = aiWorkerSessionId;
      console.log('[Chat] Resuming AI worker session with ID:', aiWorkerSessionId);
      // When resuming a session, do NOT send repository parameters
      // The repository is already available in the session workspace
    } else {
      console.log('[Chat] Starting new AI worker session - no aiWorkerSessionId available');

      // Only send repository parameters when starting a new session
      if (selectedRepo) {
        requestParams.repositoryUrl = selectedRepo;
      }

      if (baseBranch) {
        requestParams.baseBranch = baseBranch;
      }

      // Auto-commit is now always enabled
      requestParams.autoCommit = true;
    }

    // Debug: Log the exact parameters being sent
    console.log('[Chat] Final request parameters:', JSON.stringify(requestParams, null, 2));
    console.log('[Chat] Parameters being sent:', Object.keys(requestParams));

    // Always use POST to allow reading error body in response
    setStreamMethod('POST');
    setStreamBody(requestParams);
    setStreamUrl(`${API_BASE_URL}/api/execute`);

    setInput('');
    setImages([]);
  };

  const handleRetry = () => {
    if (!lastRequest || isExecuting) return;

    // Add user message for retry
    messageIdCounter.current += 1;
    const userMessage: Message = {
      id: Date.now() + messageIdCounter.current,
      chatSessionId: Number(sessionId) || 0,
      type: 'user',
      content: lastRequest.input,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);

    // Build request body with saved request data
    const requestParams: any = {
      userRequest: lastRequest.input,
    };

    if (currentSessionId) {
      requestParams.chatSessionId = currentSessionId;
      console.log('[Chat] Retrying with existing chatSession:', currentSessionId);
    }

    if (aiWorkerSessionId) {
      requestParams.resumeSessionId = aiWorkerSessionId;
      console.log('[Chat] Retrying with AI worker session ID:', aiWorkerSessionId);
      // When resuming a session, do NOT send repository parameters
      // The repository is already available in the session workspace
    } else {
      // Only send repository parameters when starting a new session
      if (lastRequest.selectedRepo) {
        requestParams.repositoryUrl = lastRequest.selectedRepo;
      }

      if (lastRequest.baseBranch) {
        requestParams.baseBranch = lastRequest.baseBranch;
      }

      // Auto-commit is now always enabled
      requestParams.autoCommit = true;
    }

    // Always use POST
    setStreamMethod('POST');
    setStreamBody(requestParams);
    setStreamUrl(`${API_BASE_URL}/api/execute`);
  };

  return (
    <SessionLayout
      selectedRepo={selectedRepo}
      baseBranch={baseBranch}
      onRepoChange={setSelectedRepo}
      onBaseBranchChange={setBaseBranch}
      repositories={repositories}
      isLoadingRepos={isLoadingRepos}
      isLocked={isLocked}
    >
      <div className="flex flex-col h-full">
      {/* Header - only show for existing sessions with messages */}
      {messages.length > 0 && (
        <div className="bg-base-100 border-b border-base-300 p-4">
          <div className="max-w-7xl mx-auto">
            <div className="flex items-center justify-between mb-2">
              {editingTitle && session ? (
                <div className="flex items-center space-x-2 flex-1">
                  <input
                    type="text"
                    value={editTitle}
                    onChange={(e) => setEditTitle(e.target.value)}
                    className="flex-1 input input-bordered"
                    autoFocus
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') handleSaveTitle();
                      if (e.key === 'Escape') handleCancelEdit();
                    }}
                  />
                  <button
                    onClick={handleSaveTitle}
                    className="btn btn-success btn-sm"
                    disabled={updateMutation.isPending}
                  >
                    Save
                  </button>
                  <button
                    onClick={handleCancelEdit}
                    className="btn btn-ghost btn-sm"
                  >
                    Cancel
                  </button>
                </div>
              ) : (
                <>
                  <h1 className="text-2xl font-bold text-base-content">
                    {session ? session.userRequest : 'Chat Session'}
                  </h1>
                  {session && (
                    <div className="flex items-center space-x-2">
                      <button
                        onClick={handleEditTitle}
                        className="btn btn-ghost btn-sm btn-circle"
                        title="Edit session title"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="h-5 w-5"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                        >
                          <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                        </svg>
                      </button>
                      <button
                        onClick={handleDeleteSession}
                        className="btn btn-ghost btn-sm btn-circle text-error"
                        title="Delete session"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="h-5 w-5"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                        >
                          <path
                            fillRule="evenodd"
                            d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </button>
                    </div>
                  )}
                </>
              )}
            </div>

            {!user?.githubAccessToken && (
              <div className="alert alert-warning mt-4">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-current shrink-0 w-6 h-6"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                <span className="text-sm">
                  Connect GitHub in settings to work with repositories
                </span>
              </div>
            )}

            {!user?.claudeAuth && (
              <div className="alert alert-error mt-4">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-current shrink-0 w-6 h-6"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                <span className="text-sm">
                  Add Claude credentials in settings to use the AI assistant
                </span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Messages or Centered Input */}
      {messages.length === 0 ? (
        /* Centered input for new session */
        <div className="flex-1 flex flex-col items-center justify-center p-6">
          {/* Auth warnings for centered view */}
          {(!user?.githubAccessToken || !user?.claudeAuth) && (
            <div className="mb-6 space-y-2 max-w-2xl w-full">
              {!user?.githubAccessToken && (
                <div className="alert alert-warning">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-current shrink-0 w-6 h-6"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                  <span className="text-sm">
                    Connect GitHub in settings to work with repositories
                  </span>
                </div>
              )}

              {!user?.claudeAuth && (
                <div className="alert alert-error">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="stroke-current shrink-0 w-6 h-6"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                  <span className="text-sm">
                    Add Claude credentials in settings to use the AI assistant
                  </span>
                </div>
              )}
            </div>
          )}

          <ChatInput
            key="centered-input"
            ref={chatInputRef}
            input={input}
            setInput={setInput}
            images={images}
            setImages={setImages}
            onSubmit={handleSubmit}
            isExecuting={isExecuting}
            selectedRepo={selectedRepo}
            setSelectedRepo={setSelectedRepo}
            baseBranch={baseBranch}
            setBaseBranch={setBaseBranch}
            repositories={repositories}
            isLoadingRepos={isLoadingRepos}
            isLocked={isLocked}
            user={user}
            centered={true}
            hideRepoSelection={true}
          />
        </div>
      ) : (
        /* Messages area with bottom input panel */
        <>
          <div className="flex-1 overflow-y-auto p-4">
            <div className="max-w-4xl mx-auto space-y-4">
              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div
                    className={`max-w-3xl rounded-lg px-4 py-2 ${
                      message.type === 'user'
                        ? 'bg-primary text-primary-content'
                        : message.type === 'error'
                        ? 'bg-error/10 text-error border border-error/20'
                        : 'bg-base-100 text-base-content border border-base-300'
                    }`}
                  >
                    <p className="text-sm whitespace-pre-wrap">{message.content}</p>

                    {/* Display images if present */}
                    {message.images && message.images.length > 0 && (
                      <div className="mt-2 grid grid-cols-2 gap-2">
                        {message.images.map((image) => (
                          <div
                            key={image.id}
                            className="relative group cursor-pointer"
                            onClick={() => setViewingImage({
                              data: image.data,
                              mediaType: image.mediaType,
                              fileName: image.fileName,
                            })}
                          >
                            <img
                              src={`data:${image.mediaType};base64,${image.data}`}
                              alt={image.fileName}
                              className="w-full h-32 object-cover rounded border border-white/20 group-hover:border-white/40 transition-colors"
                            />
                            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors rounded flex items-center justify-center">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-8 w-8 text-white opacity-0 group-hover:opacity-100 transition-opacity"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                              >
                                <path
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth={2}
                                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v3m0 0v3m0-3h3m-3 0H7"
                                />
                              </svg>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    <p className="text-xs mt-1 opacity-70">
                      {message.type === 'user' ? user?.email : message.type === 'assistant' ? 'Claude' : message.type === 'system' ? 'System' : 'Error'} • {new Date(message.timestamp).toLocaleTimeString()}
                    </p>
                    {message.type === 'error' && lastRequest && !isExecuting && (
                      <button
                        onClick={handleRetry}
                        className="mt-3 btn btn-error btn-xs"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="h-3.5 w-3.5 mr-1.5"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                        >
                          <path
                            fillRule="evenodd"
                            d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z"
                            clipRule="evenodd"
                          />
                        </svg>
                        Retry Request
                      </button>
                    )}
                  </div>
                </div>
              ))}

              {isConnected && isExecuting && (
                <div className="flex justify-start">
                  <div className="bg-base-100 border border-base-300 rounded-lg px-4 py-2">
                    <div className="flex items-center space-x-3">
                      <span className="loading loading-spinner loading-sm text-primary"></span>
                      <div className="flex flex-col">
                        <span className="text-sm text-base-content/70">Processing...</span>
                        {selectedRepo && (
                          <div className="flex items-center gap-2 mt-1">
                            {baseBranch && (
                              <span className="text-xs text-base-content/50">
                                📂 Parent: <span className="font-medium">{baseBranch}</span>
                              </span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>
          </div>

          {/* Input panel at bottom when messages exist */}
          <div className="bg-base-100 border-t border-base-300 p-6">
            <ChatInput
              key="bottom-input"
              ref={chatInputRef}
              input={input}
              setInput={setInput}
              images={images}
              setImages={setImages}
              onSubmit={handleSubmit}
              isExecuting={isExecuting}
              selectedRepo={selectedRepo}
              setSelectedRepo={setSelectedRepo}
              baseBranch={baseBranch}
              setBaseBranch={setBaseBranch}
              repositories={repositories}
              isLoadingRepos={isLoadingRepos}
              isLocked={isLocked}
              user={user}
              centered={false}
              hideRepoSelection={true}
            />
          </div>
        </>
      )}

      {/* Delete confirmation modal */}
      {deletingSession && (
        <div className="modal modal-open">
          <div className="modal-box">
            <h3 className="font-bold text-lg mb-4">
              Delete Session
            </h3>
            <p className="text-sm text-base-content/70 mb-6">
              Are you sure you want to delete this session? This action cannot be undone and will
              delete all messages in this session.
            </p>
            <div className="modal-action">
              <button
                onClick={cancelDelete}
                className="btn btn-ghost"
                disabled={deleteMutation.isPending}
              >
                Cancel
              </button>
              <button
                onClick={confirmDelete}
                className="btn btn-error"
                disabled={deleteMutation.isPending}
              >
                {deleteMutation.isPending ? 'Deleting...' : 'Delete'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Image Viewer Modal */}
      {viewingImage && (
        <ImageViewer
          imageData={viewingImage.data}
          mediaType={viewingImage.mediaType}
          fileName={viewingImage.fileName}
          onClose={() => setViewingImage(null)}
        />
      )}
      </div>
    </SessionLayout>
  );
}
