import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { sessionsApi, githubApi } from '@/lib/api';
import { useEventSource } from '@/hooks/useEventSource';
import { useAuthStore } from '@/lib/store';
import ChatInput, { type ChatInputRef, type ImageAttachment } from '@/components/ChatInput';
import { ImageViewer } from '@/components/ImageViewer';
import type { Message, GitHubRepository, ChatSession } from '@webedt/shared';

export default function Chat() {
  const { sessionId } = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const queryClient = useQueryClient();
  const user = useAuthStore((state) => state.user);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [images, setImages] = useState<ImageAttachment[]>([]);
  const [selectedRepo, setSelectedRepo] = useState('');
  const [branch, setBranch] = useState('');
  const [autoCommit, setAutoCommit] = useState(true);
  const [isExecuting, setIsExecuting] = useState(false);
  const [streamUrl, setStreamUrl] = useState<string | null>(null);
  const [streamMethod, setStreamMethod] = useState<'GET' | 'POST'>('GET');
  const [streamBody, setStreamBody] = useState<any>(null);
  const [editingTitle, setEditingTitle] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [deletingSession, setDeletingSession] = useState(false);
  const [currentSessionId, setCurrentSessionId] = useState<number | null>(
    sessionId ? Number(sessionId) : null
  );
  const [aiWorkerSessionId, setAiWorkerSessionId] = useState<string | null>(null);
  const [isLocked, setIsLocked] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messageIdCounter = useRef(0);
  const autoGeneratedTitleRef = useRef<string | null>(null);
  const hasUserEditedTitleRef = useRef(false);
  const chatInputRef = useRef<ChatInputRef>(null);
  const [lastRequest, setLastRequest] = useState<{
    input: string;
    selectedRepo: string;
    branch: string;
    autoCommit: boolean;
  } | null>(null);
  const [viewingImage, setViewingImage] = useState<{
    data: string;
    mediaType: string;
    fileName: string;
  } | null>(null);

  // Load session details first to check status
  const { data: sessionDetailsData } = useQuery({
    queryKey: ['session-details', sessionId],
    queryFn: () => sessionsApi.get(Number(sessionId)),
    enabled: !!sessionId && sessionId !== 'new',
    // Poll every 2 seconds if session is running or pending
    refetchInterval: (query) => {
      const session = query.state.data?.data;
      return session?.status === 'running' || session?.status === 'pending' ? 2000 : false;
    },
  });

  // Load existing session messages if sessionId provided
  const { data: sessionData } = useQuery({
    queryKey: ['session', sessionId],
    queryFn: () => sessionsApi.getMessages(Number(sessionId)),
    enabled: !!sessionId && sessionId !== 'new',
    // Poll every 2 seconds if session is running or pending
    refetchInterval: () => {
      const session = sessionDetailsData?.data;
      return session?.status === 'running' || session?.status === 'pending' ? 2000 : false;
    },
  });

  const session: ChatSession | undefined = sessionDetailsData?.data;

  // Load current session details to check if locked
  const { data: currentSessionData } = useQuery({
    queryKey: ['currentSession', currentSessionId],
    queryFn: async () => {
      if (!currentSessionId || currentSessionId === 0) return null;
      const response = await fetch(`/api/sessions/${currentSessionId}`, {
        credentials: 'include',
      });
      if (!response.ok) throw new Error('Failed to fetch session');
      return response.json();
    },
    enabled: !!currentSessionId && currentSessionId !== 0,
  });

  // Load repositories
  const { data: reposData, isLoading: isLoadingRepos } = useQuery({
    queryKey: ['repos'],
    queryFn: githubApi.getRepos,
    enabled: !!user?.githubAccessToken,
  });

  const repositories: GitHubRepository[] = reposData?.data || [];

  const updateMutation = useMutation({
    mutationFn: ({ id, title }: { id: number; title: string }) =>
      sessionsApi.update(id, title),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['session-details', sessionId] });
      queryClient.invalidateQueries({ queryKey: ['sessions'] });
      setEditingTitle(false);
      setEditTitle('');
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => sessionsApi.delete(id),
    onSuccess: () => {
      navigate('/dashboard');
    },
  });

  const handleEditTitle = () => {
    if (session) {
      setEditTitle(session.userRequest);
      setEditingTitle(true);
    }
  };

  const handleSaveTitle = () => {
    if (sessionId && editTitle.trim()) {
      hasUserEditedTitleRef.current = true;
      updateMutation.mutate({ id: Number(sessionId), title: editTitle.trim() });
    }
  };

  const handleCancelEdit = () => {
    setEditingTitle(false);
    setEditTitle('');
  };

  const handleDeleteSession = () => {
    setDeletingSession(true);
  };

  const confirmDelete = () => {
    if (sessionId) {
      deleteMutation.mutate(Number(sessionId));
    }
  };

  const cancelDelete = () => {
    setDeletingSession(false);
  };

  // Handle Enter key in delete modal
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (deletingSession && e.key === 'Enter' && !deleteMutation.isPending) {
        e.preventDefault();
        confirmDelete();
      }
    };

    if (deletingSession) {
      window.addEventListener('keydown', handleKeyDown);
      return () => window.removeEventListener('keydown', handleKeyDown);
    }
  }, [deletingSession, deleteMutation.isPending]);

  useEffect(() => {
    if (sessionData?.data?.messages) {
      setMessages(sessionData.data.messages);
    }
  }, [sessionData]);

  // Update locked state when session data changes
  useEffect(() => {
    if (currentSessionData?.data?.locked) {
      setIsLocked(true);
      // Also set repo/branch from session if locked
      if (currentSessionData.data.repositoryUrl) {
        setSelectedRepo(currentSessionData.data.repositoryUrl);
      }
      if (currentSessionData.data.branch) {
        setBranch(currentSessionData.data.branch);
      }
    }
  }, [currentSessionData]);

  // Load last selected repo from localStorage when repositories are loaded
  useEffect(() => {
    // Only load from localStorage if session is not locked and no repo is selected
    if (repositories.length > 0 && !selectedRepo && !isLocked) {
      const lastSelectedRepo = localStorage.getItem('lastSelectedRepo');
      if (lastSelectedRepo) {
        // Verify the repo still exists in the list
        const repoExists = repositories.some(repo => repo.cloneUrl === lastSelectedRepo);
        if (repoExists) {
          setSelectedRepo(lastSelectedRepo);
        }
      }
    }
  }, [repositories, selectedRepo, isLocked]);

  // Save selected repo to localStorage whenever it changes
  useEffect(() => {
    if (selectedRepo) {
      localStorage.setItem('lastSelectedRepo', selectedRepo);
    }
  }, [selectedRepo]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Reset state when navigating to new chat (sessionId becomes undefined)
  useEffect(() => {
    if (!sessionId) {
      setMessages([]);
      setInput('');
      setImages([]);
      setSelectedRepo('');
      setBranch('');
      setAutoCommit(true);
      setIsExecuting(false);
      setStreamUrl(null);
      setEditingTitle(false);
      setEditTitle('');
      setDeletingSession(false);
      setCurrentSessionId(null);
      setAiWorkerSessionId(null);
      setIsLocked(false);
      setLastRequest(null);
      messageIdCounter.current = 0;
      autoGeneratedTitleRef.current = null;
      hasUserEditedTitleRef.current = false;
    }
  }, [sessionId]);

  // Sync aiWorkerSessionId from query data when loading an existing session
  useEffect(() => {
    if (currentSessionData?.data?.aiWorkerSessionId) {
      console.log(
        '[Chat] Syncing aiWorkerSessionId from query:',
        currentSessionData.data.aiWorkerSessionId
      );
      setAiWorkerSessionId(currentSessionData.data.aiWorkerSessionId);
    }
  }, [currentSessionData]);

  // Auto-connect to stream when navigating from Dashboard with stream params
  useEffect(() => {
    // Check if we came from Dashboard with stream params
    const state = location.state as any;
    if (state?.startStream && state?.streamParams && !streamUrl) {
      console.log('[Chat] Auto-starting stream from navigation state:', state.streamParams);

      const { userRequest } = state.streamParams;

      // Check if userRequest is an array (images present)
      if (Array.isArray(userRequest)) {
        // Use POST for requests with images
        setStreamMethod('POST');
        setStreamBody(state.streamParams);
        setStreamUrl(`/api/execute`);
      } else {
        // Use GET for text-only requests
        setStreamMethod('GET');
        setStreamBody(null);
        const params = new URLSearchParams();
        Object.entries(state.streamParams).forEach(([key, value]) => {
          if (value !== undefined && value !== null) {
            params.append(key, String(value));
          }
        });
        setStreamUrl(`/api/execute?${params}`);
      }

      setIsExecuting(true);

      // Clear the navigation state to prevent re-triggering
      navigate(location.pathname, { replace: true, state: {} });
    }
  }, [location.state, streamUrl, navigate, location.pathname]);

  // Reset title edit tracking when switching to a different session
  useEffect(() => {
    if (sessionId) {
      autoGeneratedTitleRef.current = null;
      hasUserEditedTitleRef.current = false;
    }
  }, [sessionId]);

  const { isConnected } = useEventSource(streamUrl, {
    method: streamMethod,
    body: streamBody,
    onMessage: (event) => {
      // Log all events to see what we're receiving
      console.log('Received SSE event:', event);
      console.log('Full event data structure:', JSON.stringify(event, null, 2));

      const { eventType, data } = event;

      // Handle session-created event - update URL to the actual session ID
      if (eventType === 'session-created' && data?.chatSessionId) {
        console.log('[Chat] Session created with ID:', data.chatSessionId);
        setCurrentSessionId(data.chatSessionId);

        // Navigate to the actual session URL if we're on /chat/new
        if (!sessionId || sessionId === 'new') {
          console.log('[Chat] Navigating to session:', data.chatSessionId);
          navigate(`/chat/${data.chatSessionId}`, { replace: true });
        }

        // Don't display this as a message
        return;
      }

      // Capture AI worker session ID from connected event
      if (eventType === 'connected' && data?.sessionId) {
        console.log('[Chat] Captured aiWorkerSessionId from connected event:', data.sessionId);
        setAiWorkerSessionId(data.sessionId);
      }

      // Skip system events
      if (eventType === 'connected' || eventType === 'completed') {
        return;
      }

      // Extract content from various possible locations
      let content: string | null = null;
      let messageType: 'assistant' | 'system' = 'assistant';
      let eventLabel = '';

      // Skip if data is undefined or null
      if (!data) {
        console.log('Skipping event with no data:', event);
        return;
      }

      // Extract content from different event types (matching server-side logic)
      if (data.type === 'message' && data.message) {
        content = data.message;
        eventLabel = '💬';
      } else if (data.type === 'session_name' && data.sessionName) {
        // Session name - auto-save if not manually edited
        const newTitle = data.sessionName;
        content = `Session: ${newTitle}`;
        eventLabel = '📝';

        // Auto-update the session title if:
        // 1. User hasn't manually edited the title
        // 2. Current title is the default "Resumed session" OR matches a previous auto-generated title
        if (sessionId && session && !hasUserEditedTitleRef.current) {
          const currentTitle = session.userRequest;
          const isDefaultTitle = currentTitle === 'Resumed session';
          const isPreviousAutoTitle = autoGeneratedTitleRef.current && currentTitle === autoGeneratedTitleRef.current;

          if (isDefaultTitle || isPreviousAutoTitle || !autoGeneratedTitleRef.current) {
            console.log('[Chat] Auto-updating session title to:', newTitle);
            autoGeneratedTitleRef.current = newTitle;
            updateMutation.mutate({ id: Number(sessionId), title: newTitle });
          }
        }
      } else if (data.type === 'assistant_message' && data.data) {
        const msgData = data.data;

        // Handle assistant message with Claude response
        if (msgData.type === 'assistant' && msgData.message?.content) {
          const contentBlocks = msgData.message.content;
          if (Array.isArray(contentBlocks)) {
            const textParts = contentBlocks
              .filter((block: any) => block.type === 'text' && block.text)
              .map((block: any) => block.text);
            if (textParts.length > 0) {
              content = textParts.join('\n');
              eventLabel = '🤖';
            }
          }
        }
        // Handle result type (final response)
        else if (msgData.type === 'result' && msgData.result) {
          content = typeof msgData.result === 'string' ? msgData.result : JSON.stringify(msgData.result, null, 2);
          eventLabel = '✅';
        }
        // Skip system init messages
        else if (msgData.type === 'system' && msgData.subtype === 'init') {
          console.log('[Chat] Skipping system init message');
          return;
        }
      }
      // Fallback to direct fields
      else if (typeof data === 'string') {
        content = data;
      } else if (data.message) {
        content = data.message;
      } else if (data.content) {
        if (Array.isArray(data.content)) {
          const textBlocks = data.content
            .filter((block: any) => block.type === 'text' && block.text)
            .map((block: any) => block.text);
          if (textBlocks.length > 0) {
            content = textBlocks.join('\n');
          }
        } else if (typeof data.content === 'string') {
          content = data.content;
        }
      } else if (data.text) {
        content = data.text;
      } else if (data.result) {
        content = typeof data.result === 'string' ? data.result : JSON.stringify(data.result, null, 2);
      }

      // Skip if no meaningful content
      if (!content) {
        console.log('Skipping event with no content:', event);
        console.log('Data keys:', typeof data === 'object' ? Object.keys(data) : typeof data);
        return;
      }

      // Add event label if present
      const finalContent = eventLabel ? `${eventLabel}\n${content}` : content;

      messageIdCounter.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + messageIdCounter.current,
          chatSessionId: Number(sessionId) || 0,
          type: messageType,
          content: finalContent,
          timestamp: new Date(),
        },
      ]);
    },
    onConnected: () => {
      setIsExecuting(true);
    },
    onCompleted: (data) => {
      setIsExecuting(false);
      setStreamUrl(null);
      // Capture session ID from completion event
      if (data?.chatSessionId) {
        console.log('[Chat] Execution completed, setting currentSessionId:', data.chatSessionId);
        setCurrentSessionId(data.chatSessionId);
        // Invalidate the query to refetch session data with aiWorkerSessionId
        queryClient.invalidateQueries({ queryKey: ['currentSession', data.chatSessionId] });

        // Navigate to the session URL if not already there
        if (!sessionId || Number(sessionId) !== data.chatSessionId) {
          console.log('[Chat] Navigating to session:', data.chatSessionId);
          navigate(`/chat/${data.chatSessionId}`, { replace: true });
        }
      }
      // Refocus input after processing completes (with delay to ensure DOM updates)
      setTimeout(() => {
        chatInputRef.current?.focus();
      }, 100);
    },
    onError: (error) => {
      console.error('Stream error:', error);
      messageIdCounter.current += 1;
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + messageIdCounter.current,
          chatSessionId: Number(sessionId) || 0,
          type: 'error',
          content: error.message,
          timestamp: new Date(),
        },
      ]);
      setIsExecuting(false);
      setStreamUrl(null);
      // Refocus input after error (with delay to ensure DOM updates)
      setTimeout(() => {
        chatInputRef.current?.focus();
      }, 100);
    },
    autoReconnect: false, // Disable auto-reconnect to prevent infinite loops
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if ((!input.trim() && images.length === 0) || isExecuting) return;

    // Set executing state immediately to prevent duplicate submissions
    setIsExecuting(true);

    // Save last request for retry functionality
    setLastRequest({
      input: input.trim(),
      selectedRepo,
      branch,
      autoCommit,
    });

    // Add user message
    messageIdCounter.current += 1;
    const userMessage: Message = {
      id: Date.now() + messageIdCounter.current,
      chatSessionId: Number(sessionId) || 0,
      type: 'user',
      content: images.length > 0
        ? `${input}\n[${images.length} image${images.length > 1 ? 's' : ''} attached]`
        : input,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);

    // Build userRequest - either string or content blocks
    let userRequestParam: string | any[];

    if (images.length > 0) {
      // Create content blocks for multimodal request
      const contentBlocks: any[] = [];

      // Add text block if there's text
      if (input.trim()) {
        contentBlocks.push({
          type: 'text',
          text: input.trim(),
        });
      }

      // Add image blocks
      images.forEach((image) => {
        contentBlocks.push({
          type: 'image',
          source: {
            type: 'base64',
            media_type: image.mediaType,
            data: image.data,
          },
        });
      });

      userRequestParam = contentBlocks;
    } else {
      userRequestParam = input.trim();
    }

    // Build request parameters
    const requestParams: any = {
      userRequest: userRequestParam,
    };

    if (currentSessionId) {
      requestParams.chatSessionId = currentSessionId;
      console.log('[Chat] Continuing existing chatSession:', currentSessionId);
    }

    if (selectedRepo) {
      requestParams.repositoryUrl = selectedRepo;
    }

    if (branch) {
      requestParams.branch = branch;
    }

    if (autoCommit) {
      requestParams.autoCommit = true;
    }

    console.log('[Chat] Session resumption check:', {
      currentSessionId,
      aiWorkerSessionId,
      fromQuery: currentSessionData?.data?.aiWorkerSessionId,
    });

    if (aiWorkerSessionId) {
      requestParams.resumeSessionId = aiWorkerSessionId;
      console.log('[Chat] Resuming AI worker session with ID:', aiWorkerSessionId);
    } else {
      console.log('[Chat] Starting new AI worker session - no aiWorkerSessionId available');
    }

    // Use POST for requests with images to avoid URL length limits
    if (images.length > 0) {
      // Use POST for large requests with images
      setStreamMethod('POST');
      setStreamBody(requestParams);
      setStreamUrl(`/api/execute`);
    } else {
      // Use GET with query params for text-only requests
      setStreamMethod('GET');
      setStreamBody(null);
      const params = new URLSearchParams();
      Object.entries(requestParams).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          params.append(key, String(value));
        }
      });
      setStreamUrl(`/api/execute?${params}`);
    }

    setInput('');
    setImages([]);
  };

  const handleRetry = () => {
    if (!lastRequest || isExecuting) return;

    // Add user message for retry
    messageIdCounter.current += 1;
    const userMessage: Message = {
      id: Date.now() + messageIdCounter.current,
      chatSessionId: Number(sessionId) || 0,
      type: 'user',
      content: lastRequest.input,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);

    // Build stream URL with saved request data
    const params = new URLSearchParams({
      userRequest: lastRequest.input,
    });

    if (currentSessionId) {
      params.append('chatSessionId', String(currentSessionId));
      console.log('[Chat] Retrying with existing chatSession:', currentSessionId);
    }

    if (lastRequest.selectedRepo) {
      params.append('repositoryUrl', lastRequest.selectedRepo);
    }

    if (lastRequest.branch) {
      params.append('branch', lastRequest.branch);
    }

    if (lastRequest.autoCommit) {
      params.append('autoCommit', 'true');
    }

    if (aiWorkerSessionId) {
      params.append('resumeSessionId', aiWorkerSessionId);
      console.log('[Chat] Retrying with AI worker session ID:', aiWorkerSessionId);
    }

    setStreamUrl(`/api/execute?${params}`);
  };

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)]">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 p-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center justify-between mb-2">
            {editingTitle && session ? (
              <div className="flex items-center space-x-2 flex-1">
                <input
                  type="text"
                  value={editTitle}
                  onChange={(e) => setEditTitle(e.target.value)}
                  className="flex-1 rounded-md border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white shadow-sm focus:border-blue-500 focus:ring-blue-500"
                  autoFocus
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') handleSaveTitle();
                    if (e.key === 'Escape') handleCancelEdit();
                  }}
                />
                <button
                  onClick={handleSaveTitle}
                  className="inline-flex items-center px-3 py-2 border border-transparent text-sm font-medium rounded text-white bg-green-600 hover:bg-green-700"
                  disabled={updateMutation.isPending}
                >
                  Save
                </button>
                <button
                  onClick={handleCancelEdit}
                  className="inline-flex items-center px-3 py-2 border border-gray-300 dark:border-gray-600 text-sm font-medium rounded text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <>
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                  {session ? session.userRequest : 'Chat Session'}
                </h1>
                {session && (
                  <div className="flex items-center space-x-2">
                    <button
                      onClick={handleEditTitle}
                      className="text-gray-500 hover:text-blue-600 dark:text-gray-400 dark:hover:text-blue-400"
                      title="Edit session title"
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="h-5 w-5"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                      </svg>
                    </button>
                    <button
                      onClick={handleDeleteSession}
                      className="text-gray-500 hover:text-red-600 dark:text-gray-400 dark:hover:text-red-400"
                      title="Delete session"
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="h-5 w-5"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fillRule="evenodd"
                          d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                          clipRule="evenodd"
                        />
                      </svg>
                    </button>
                  </div>
                )}
              </>
            )}
          </div>

          {isLocked && (
            <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-900/20 rounded-md">
              <p className="text-sm text-blue-800 dark:text-blue-200">
                This session is locked to repository {selectedRepo} on branch {branch}. Repository and branch cannot be changed.
              </p>
            </div>
          )}

          {!user?.githubAccessToken && (
            <div className="mt-4 p-3 bg-yellow-50 dark:bg-yellow-900/20 rounded-md">
              <p className="text-sm text-yellow-800 dark:text-yellow-200">
                Connect GitHub in settings to work with repositories
              </p>
            </div>
          )}

          {!user?.claudeAuth && (
            <div className="mt-4 p-3 bg-red-50 dark:bg-red-900/20 rounded-md">
              <p className="text-sm text-red-800 dark:text-red-200">
                Add Claude credentials in settings to use the AI assistant
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Messages or Centered Input */}
      {messages.length === 0 ? (
        /* Centered input for new session */
        <div className="flex-1 flex items-center justify-center p-6">
          <ChatInput
            ref={chatInputRef}
            input={input}
            setInput={setInput}
            images={images}
            setImages={setImages}
            onSubmit={handleSubmit}
            isExecuting={isExecuting}
            selectedRepo={selectedRepo}
            setSelectedRepo={setSelectedRepo}
            branch={branch}
            setBranch={setBranch}
            autoCommit={autoCommit}
            setAutoCommit={setAutoCommit}
            repositories={repositories}
            isLoadingRepos={isLoadingRepos}
            isLocked={isLocked}
            user={user}
            centered={true}
          />
        </div>
      ) : (
        /* Messages area with bottom input panel */
        <>
          <div className="flex-1 overflow-y-auto p-4">
            <div className="max-w-4xl mx-auto space-y-4">
              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div
                    className={`max-w-3xl rounded-lg px-4 py-2 ${
                      message.type === 'user'
                        ? 'bg-blue-600 text-white'
                        : message.type === 'error'
                        ? 'bg-red-100 dark:bg-red-900/20 text-red-800 dark:text-red-200'
                        : 'bg-white dark:bg-gray-800 text-gray-900 dark:text-white border border-gray-200 dark:border-gray-700'
                    }`}
                  >
                    <p className="text-sm whitespace-pre-wrap">{message.content}</p>

                    {/* Display images if present */}
                    {message.images && message.images.length > 0 && (
                      <div className="mt-2 grid grid-cols-2 gap-2">
                        {message.images.map((image) => (
                          <div
                            key={image.id}
                            className="relative group cursor-pointer"
                            onClick={() => setViewingImage({
                              data: image.data,
                              mediaType: image.mediaType,
                              fileName: image.fileName,
                            })}
                          >
                            <img
                              src={`data:${image.mediaType};base64,${image.data}`}
                              alt={image.fileName}
                              className="w-full h-32 object-cover rounded border border-white/20 group-hover:border-white/40 transition-colors"
                            />
                            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors rounded flex items-center justify-center">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-8 w-8 text-white opacity-0 group-hover:opacity-100 transition-opacity"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                              >
                                <path
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth={2}
                                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v3m0 0v3m0-3h3m-3 0H7"
                                />
                              </svg>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    <p className="text-xs mt-1 opacity-70">
                      {new Date(message.timestamp).toLocaleTimeString()}
                    </p>
                    {message.type === 'error' && lastRequest && !isExecuting && (
                      <button
                        onClick={handleRetry}
                        className="mt-3 inline-flex items-center px-3 py-1.5 border border-transparent text-xs font-medium rounded text-white bg-red-600 hover:bg-red-700 dark:bg-red-700 dark:hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="h-3.5 w-3.5 mr-1.5"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                        >
                          <path
                            fillRule="evenodd"
                            d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z"
                            clipRule="evenodd"
                          />
                        </svg>
                        Retry Request
                      </button>
                    )}
                  </div>
                </div>
              ))}

              {isConnected && isExecuting && (
                <div className="flex justify-start">
                  <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg px-4 py-2">
                    <div className="flex items-center space-x-2">
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
                      <span className="text-sm text-gray-600 dark:text-gray-400">Processing...</span>
                    </div>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>
          </div>

          {/* Input panel at bottom when messages exist */}
          <div className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-6">
            <ChatInput
              ref={chatInputRef}
              input={input}
              setInput={setInput}
              images={images}
              setImages={setImages}
              onSubmit={handleSubmit}
              isExecuting={isExecuting}
              selectedRepo={selectedRepo}
              setSelectedRepo={setSelectedRepo}
              branch={branch}
              setBranch={setBranch}
              autoCommit={autoCommit}
              setAutoCommit={setAutoCommit}
              repositories={repositories}
              isLoadingRepos={isLoadingRepos}
              isLocked={isLocked}
              user={user}
              centered={false}
            />
          </div>
        </>
      )}

      {/* Delete confirmation modal */}
      {deletingSession && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 dark:bg-gray-900 dark:bg-opacity-80 overflow-y-auto h-full w-full flex items-center justify-center z-50">
          <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-xl max-w-md w-full mx-4">
            <h3 className="text-lg font-medium text-gray-900 dark:text-white mb-4">
              Delete Session
            </h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
              Are you sure you want to delete this session? This action cannot be undone and will
              delete all messages in this session.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={cancelDelete}
                className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-md text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
                disabled={deleteMutation.isPending}
              >
                Cancel
              </button>
              <button
                onClick={confirmDelete}
                className="px-4 py-2 border border-transparent rounded-md text-sm font-medium text-white bg-red-600 hover:bg-red-700 disabled:opacity-50"
                disabled={deleteMutation.isPending}
              >
                {deleteMutation.isPending ? 'Deleting...' : 'Delete'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Image Viewer Modal */}
      {viewingImage && (
        <ImageViewer
          imageData={viewingImage.data}
          mediaType={viewingImage.mediaType}
          fileName={viewingImage.fileName}
          onClose={() => setViewingImage(null)}
        />
      )}
    </div>
  );
}
